import { DATENBANK } from "../../verein.config.js";
const anmeldung=globalThis.SchiriSeitenAnmeldung?.anmeldung||globalThis.SchiriAnmeldung.erstelleAnmeldung({adresse:DATENBANK.adresse,oeffentlicherSchluessel:DATENBANK.oeffentlicherSchluessel});
const rpc=globalThis.SchiriRpc.erstelleRpc({adresse:DATENBANK.adresse,oeffentlicherSchluessel:DATENBANK.oeffentlicherSchluessel});
const $=id=>document.getElementById(id); const ich=()=>anmeldung?.lesen(); let eintraege=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function neu(){$("bestand-formular").reset();$("bestand-id").value="";$("bestand-anzahl").value="1";$("bestand-meldung").textContent="";loeschStandZuruecksetzen();}
// Loeschen ohne Browserdialog (Hausregel): der Knopf fragt selbst nach,
// indem er beim ersten Druck zur Rueckfrage wird. Ein zweiter Druck
// loescht, jede andere Aktion setzt ihn zurueck.
function loeschStandZuruecksetzen(){const k=$("bestand-loeschen");if(!k)return;k.hidden=!$("bestand-id").value;k.dataset.sicher="";k.textContent="Eintrag löschen";}
async function laden(){const p=ich();const {data,error}=await rpc.rpc("schiri_ausruestungsbestand_liste",{p_schiedsrichter_id:p.id,p_pin:p.pin});if(error){$("bestand-liste").textContent="Bestand konnte nicht geladen werden.";return;}eintraege=Array.isArray(data)?data:[];$("bestand-liste").innerHTML=eintraege.length?eintraege.map(x=>`<button class="vorschlag-eintrag" data-id="${x.id}"><strong>${esc(x.bezeichnung||x.kategorie)}</strong><span>${esc([x.farbe,x.groesse,x.aermellaenge,x.anzahl+"×",x.zustand].filter(Boolean).join(" · "))}</span></button>`).join(""):"<p>Noch nichts eingetragen.</p>";document.querySelectorAll(".vorschlag-eintrag").forEach(b=>b.onclick=()=>fuellen(b.dataset.id));}
function fuellen(id){const x=eintraege.find(e=>e.id===id);if(!x)return;$("bestand-id").value=x.id;$("bestand-kategorie").value=x.kategorie;$("bestand-bezeichnung").value=x.bezeichnung||"";$("bestand-farbe").value=x.farbe||"";$("bestand-groesse").value=x.groesse||"";$("bestand-aermel").value=x.aermellaenge||"";$("bestand-anzahl").value=x.anzahl||1;$("bestand-zustand").value=x.zustand;$("bestand-anmerkung").value=x.anmerkung||"";loeschStandZuruecksetzen();window.scrollTo({top:0,behavior:"smooth"});}
$("bestand-formular").onsubmit=async e=>{e.preventDefault();const p=ich();$("bestand-meldung").textContent="Wird gespeichert …";const {error}=await rpc.rpc("schiri_ausruestungsbestand_speichern",{p_schiedsrichter_id:p.id,p_pin:p.pin,p_kategorie:$("bestand-kategorie").value,p_bezeichnung:$("bestand-bezeichnung").value.trim()||null,p_farbe:$("bestand-farbe").value.trim()||null,p_groesse:$("bestand-groesse").value.trim()||null,p_aermellaenge:$("bestand-aermel").value||null,p_anzahl:Number($("bestand-anzahl").value),p_zustand:$("bestand-zustand").value,p_anmerkung:$("bestand-anmerkung").value.trim()||null,p_id:$("bestand-id").value||null});$("bestand-meldung").textContent=error?"Speichern fehlgeschlagen: "+error.message:"Gespeichert.";if(!error){neu();await laden();}};$("bestand-neu").onclick=neu;
$("bestand-loeschen").onclick=async e=>{const k=e.currentTarget;const id=$("bestand-id").value;if(!id)return;if(k.dataset.sicher!=="ja"){k.dataset.sicher="ja";k.textContent="Wirklich löschen?";return;}const p=ich();$("bestand-meldung").textContent="Wird gelöscht …";const {error}=await rpc.rpc("schiri_ausruestungsbestand_loeschen",{p_schiedsrichter_id:p.id,p_pin:p.pin,p_id:id});$("bestand-meldung").textContent=error?"Löschen fehlgeschlagen: "+error.message:"Eintrag gelöscht.";if(!error){neu();await laden();}else loeschStandZuruecksetzen();};
if(ich()){$("bestand-inhalt").hidden=false;laden();}else $("bestand-zugang").hidden=false;
