-- v96_szenario_serie_deterministisch (29.08.2026)
--
-- Nachtrag zu v94, gefunden durch Pruefung 10 der Testreihe: nach einer
-- falschen Antwort meldete der Modus "Serie 1" statt "Serie 0".
--
-- ============================================================
--  Warum
-- ============================================================
--
-- Die Serie zaehlt die zuletzt gespielten Szenarien rueckwaerts, bis
-- der erste Fehler kommt. Sortiert wurde nach beantwortet_am - und
-- dessen Default war now(). now() ist der Beginn der TRANSAKTION, nicht
-- der Augenblick des Einfuegens. Mehrere Antworten in einer Transaktion
-- bekommen damit exakt dieselbe Zeit, die Sortierung ist beliebig, und
-- die laufende Summe faellt auf eine andere Zeile.
--
-- Im Alltag faellt das nicht auf, weil jeder RPC-Aufruf seine eigene
-- Transaktion ist. Verlassen sollte man sich darauf trotzdem nicht: zwei
-- Antworten in derselben Sekunde reichen fuer denselben Gleichstand, und
-- eine Serie, die gelegentlich falsch zaehlt, ist in einem Spiel
-- schlimmer als gar keine.
--
-- Zwei Aenderungen:
--   1. lfd - eine aufsteigende Zahl. Sie ist die einzige verlaessliche
--      Reihenfolge und haengt an keiner Uhr.
--   2. beantwortet_am bekommt clock_timestamp() statt now(): der
--      Zeitpunkt der Antwort, nicht der des Transaktionsbeginns.
--
-- Und die Serie wandert in eine eigene Funktion, damit es sie nur
-- einmal gibt. Vorher stand dieselbe Fensterabfrage in zwei RPCs - der
-- sicherste Weg, einen Fehler nur zur Haelfte zu beheben.

alter table public.szenario_antworten
  add column if not exists lfd bigint generated by default as identity;

alter table public.szenario_antworten
  alter column beantwortet_am set default clock_timestamp();

create index if not exists idx_szenario_antworten_lfd
  on public.szenario_antworten (schiedsrichter_id, lfd desc);

comment on column public.szenario_antworten.lfd is
  'Aufsteigende Reihenfolge der Antworten. Massgeblich fuer die Serie - beantwortet_am kann bei zwei Antworten in derselben Sekunde gleich sein (siehe v96).';

-- ============================================================
--  Die Serie, an genau einer Stelle
-- ============================================================

create or replace function public.szenario_serie(p_schiedsrichter_id uuid)
returns integer
language sql
stable
security definer
set search_path to public
as $function$
  select count(*)::int from (
    select sum(case when a.bewertung = 'komplett' then 0 else 1 end)
             over (order by a.lfd desc rows between unbounded preceding and current row) as fehler
    from szenario_antworten a
    where a.schiedsrichter_id = p_schiedsrichter_id
  ) t where t.fehler = 0;
$function$;

comment on function public.szenario_serie(uuid) is
  'Wie viele der zuletzt gespielten Szenarien hintereinander komplett richtig waren. Bricht beim ersten Fehler ab.';

revoke all on function public.szenario_serie(uuid) from public;

-- ============================================================
--  Beide Aufrufer auf die eine Funktion umstellen
-- ============================================================

create or replace function public.szenario_antwort_pruefen(
  p_schiedsrichter_id uuid,
  p_pin text,
  p_szenario_id uuid,
  p_fortsetzung text,
  p_strafe text,
  p_fortsetzung_fuer text default null,
  p_strafe_fuer text default null,
  p_zusatz jsonb default '{}'::jsonb
)
returns table (
  bewertung text,
  punkte smallint,
  fortsetzung_richtig boolean,
  richtung_richtig boolean,
  strafe_richtig boolean,
  strafe_ziel_richtig boolean,
  zusatz_ergebnis jsonb,
  loesung jsonb,
  erklaerung text,
  versuch_nr smallint,
  serie integer
)
language plpgsql
security definer
set search_path to public
as $function$
declare
  v_pin text; v_aktiv boolean; l record;
  v_fuer text; v_strafe_fuer text;
  v_fortsetzung_ok boolean; v_richtung_ok boolean;
  v_strafe_ok boolean; v_strafziel_ok boolean;
  v_zusatz jsonb := '[]'::jsonb;
  v_zusatz_alle_ok boolean := true;
  v_punkte smallint; v_bewertung text; v_versuch smallint;
  z record;
begin
  select s.pin, s.aktiv into v_pin, v_aktiv
  from schiedsrichter s where s.id = p_schiedsrichter_id;
  if v_pin is null or v_pin <> p_pin or not coalesce(v_aktiv, false) then
    raise exception 'PIN falsch';
  end if;

  select * into l from szenario_loesungen where szenario_id = p_szenario_id;
  if not found then
    raise exception 'Szenario ohne Loesung';
  end if;
  if not exists (select 1 from entscheidungs_szenarien s where s.id = p_szenario_id and s.aktiv) then
    raise exception 'Szenario nicht freigegeben';
  end if;

  -- Eingaben auf die Form bringen, in der auch die Loesung steht.
  -- Weiterspielen und Schiedsrichter-Ball haben keine Richtung, "keine
  -- Strafe" hat keinen Betroffenen. Ohne diese Normalisierung waere ein
  -- vom Browser mitgeschicktes Restfeld ein falsches Ergebnis, obwohl
  -- der Tipp stimmt.
  v_fuer := case when p_fortsetzung in ('weiterspielen', 'sr_ball')
                 then null else nullif(p_fortsetzung_fuer, '') end;
  v_strafe_fuer := case when p_strafe = 'keine'
                        then null else nullif(p_strafe_fuer, '') end;

  v_fortsetzung_ok := p_fortsetzung = l.spielfortsetzung;
  v_richtung_ok    := v_fuer is not distinct from l.fortsetzung_fuer;
  v_strafe_ok      := p_strafe = l.persoenliche_strafe;
  v_strafziel_ok   := v_strafe_fuer is not distinct from l.strafe_fuer_mannschaft;

  for z in
    select zf.id, zf.frage_text,
           p_zusatz ->> zf.id::text            as gewaehlt,
           l.zusatz_antworten ->> zf.id::text  as richtig
    from szenario_zusatzfragen zf
    where zf.szenario_id = p_szenario_id
    order by zf.position
  loop
    v_zusatz := v_zusatz || jsonb_build_object(
      'id', z.id, 'frage_text', z.frage_text,
      'gewaehlt', z.gewaehlt, 'richtig', z.richtig,
      'ok', z.gewaehlt is not distinct from z.richtig);
    if z.gewaehlt is distinct from z.richtig then
      v_zusatz_alle_ok := false;
    end if;
  end loop;

  -- Zwei Achsen, zwei Punkte. Die Richtung gehoert zur Fortsetzung und
  -- der Betroffene zur Strafe - "Freistoss fuer die falsche Mannschaft"
  -- ist keine halbe richtige Entscheidung.
  v_punkte := (case when v_fortsetzung_ok and v_richtung_ok then 1 else 0 end)
            + (case when v_strafe_ok and v_strafziel_ok then 1 else 0 end);

  v_bewertung := case
    when v_punkte = 2 and v_zusatz_alle_ok then 'komplett'
    when v_punkte = 0 then 'falsch'
    else 'teilweise' end;

  select coalesce(max(a.versuch_nr), 0)::smallint + 1 into v_versuch
  from szenario_antworten a
  where a.schiedsrichter_id = p_schiedsrichter_id and a.szenario_id = p_szenario_id;

  insert into szenario_antworten (
    schiedsrichter_id, szenario_id,
    gewaehlte_fortsetzung, gewaehlte_fortsetzung_fuer,
    gewaehlte_strafe, gewaehlte_strafe_fuer,
    gewaehlte_zusatz, bewertung, punkte, versuch_nr)
  values (
    p_schiedsrichter_id, p_szenario_id,
    p_fortsetzung, v_fuer, p_strafe, v_strafe_fuer,
    coalesce(p_zusatz, '{}'::jsonb), v_bewertung, v_punkte, v_versuch);

  return query select
    v_bewertung, v_punkte,
    v_fortsetzung_ok, v_richtung_ok, v_strafe_ok, v_strafziel_ok,
    v_zusatz,
    jsonb_build_object(
      'spielfortsetzung', l.spielfortsetzung,
      'fortsetzung_fuer', l.fortsetzung_fuer,
      'persoenliche_strafe', l.persoenliche_strafe,
      'strafe_fuer_mannschaft', l.strafe_fuer_mannschaft,
      'strafe_fuer_rolle', l.strafe_fuer_rolle,
      'strafe_rueckennummer', l.strafe_rueckennummer),
    l.erklaerung, v_versuch, public.szenario_serie(p_schiedsrichter_id);
end;
$function$;

create or replace function public.szenario_statistik(p_schiedsrichter_id uuid, p_pin text)
returns table (
  szenarien_gesamt integer,
  gespielt integer,
  offen integer,
  komplett integer,
  quote numeric,
  serie integer
)
language plpgsql
security definer
set search_path to public
as $function$
declare
  v_pin text; v_aktiv boolean;
begin
  select s.pin, s.aktiv into v_pin, v_aktiv
  from schiedsrichter s where s.id = p_schiedsrichter_id;
  if v_pin is null or v_pin <> p_pin or not coalesce(v_aktiv, false) then
    raise exception 'PIN falsch';
  end if;

  return query
  with aktiv as (select count(*)::int as n from entscheidungs_szenarien where aktiv),
  meine as (
    select a.szenario_id, count(*) filter (where a.bewertung = 'komplett') as k
    from szenario_antworten a
    join entscheidungs_szenarien s on s.id = a.szenario_id and s.aktiv
    where a.schiedsrichter_id = p_schiedsrichter_id
    group by a.szenario_id
  )
  select aktiv.n,
         (select count(*)::int from meine),
         aktiv.n - (select count(*)::int from meine),
         (select count(*)::int from meine where k > 0),
         case when (select count(*) from meine) = 0 then 0::numeric
              else round(100.0 * (select count(*) from meine where k > 0)
                               / (select count(*) from meine), 0) end,
         public.szenario_serie(p_schiedsrichter_id)
  from aktiv;
end;
$function$;
